name: Build
on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '*.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu"
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Create settings.gradle.kts
        run: |
          cat > settings.gradle.kts << 'EOF'
          rootProject.name = "StreamPlay"
          
          dependencyResolutionManagement {
              repositories {
                  google()
                  mavenCentral()
                  maven("https://jitpack.io")
              }
          }
          EOF
      
      - name: Create local.properties
        run: |
          cat > local.properties << 'EOF'
          TMDB_API=
          CINEMATV_API=
          SFMOVIES_API=
          ZSHOW_API=
          DUMP_API=
          DUMP_KEY=
          CRUNCHYROLL_BASIC_TOKEN=
          CRUNCHYROLL_REFRESH_TOKEN=
          MOVIE_API=
          ANICHI_API=
          Whvx_API=
          CatflixAPI=
          ConsumetAPI=
          FlixHQAPI=
          WhvxAPI=
          WhvxT=
          SharmaflixApikey=
          SharmaflixApi=
          Theyallsayflix=
          GojoAPI=
          HianimeAPI=
          Vidsrccc=
          WASMAPI=
          KissKh=
          KisskhSub=
          SUPERSTREAM_THIRD_API=
          SUPERSTREAM_FOURTH_API=
          SUPERSTREAM_FIRST_API=
          StreamPlayAPI=
          PROXYAPI=
          KAISVA=
          MOVIEBOX_SECRET_KEY_ALT=
          MOVIEBOX_SECRET_KEY_DEFAULT=
          KAIDEC=
          EOF
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      
      - name: Build extensions
        run: gradle make makePluginsJson --stacktrace
      
      - name: Push builds
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -B builds
          git add **/build/*.cs3 build/plugins.json
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push -f origin builds          CRUNCHYROLL_REFRESH_TOKEN=
          MOVIE_API=
          ANICHI_API=
          Whvx_API=
          CatflixAPI=
          ConsumetAPI=
          FlixHQAPI=
          WhvxAPI=
          WhvxT=
          SharmaflixApikey=
          SharmaflixApi=
          Theyallsayflix=
          GojoAPI=
          HianimeAPI=
          Vidsrccc=
          WASMAPI=
          KissKh=
          KisskhSub=
          SUPERSTREAM_THIRD_API=
          SUPERSTREAM_FOURTH_API=
          SUPERSTREAM_FIRST_API=
          StreamPlayAPI=
          PROXYAPI=
          KAISVA=
          MOVIEBOX_SECRET_KEY_ALT=
          MOVIEBOX_SECRET_KEY_DEFAULT=
          KAIDEC=
          EOF
      
      - name: Build extensions
        run: gradle make makePluginsJson
      
      - name: Push builds
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -B builds
          git add **/build/*.cs3 build/plugins.json
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push -f origin builds          CRUNCHYROLL_REFRESH_TOKEN=placeholder
          MOVIE_API=placeholder
          ANICHI_API=placeholder
          Whvx_API=placeholder
          CatflixAPI=placeholder
          ConsumetAPI=placeholder
          FlixHQAPI=placeholder
          WhvxAPI=placeholder
          WhvxT=placeholder
          SharmaflixApikey=placeholder
          SharmaflixApi=placeholder
          Theyallsayflix=placeholder
          GojoAPI=placeholder
          HianimeAPI=placeholder
          Vidsrccc=placeholder
          WASMAPI=placeholder
          KissKh=placeholder
          KisskhSub=placeholder
          SUPERSTREAM_THIRD_API=placeholder
          SUPERSTREAM_FOURTH_API=placeholder
          SUPERSTREAM_FIRST_API=placeholder
          StreamPlayAPI=placeholder
          PROXYAPI=placeholder
          KAISVA=placeholder
          MOVIEBOX_SECRET_KEY_ALT=placeholder
          MOVIEBOX_SECRET_KEY_DEFAULT=placeholder
          KAIDEC=placeholder
          EOF
      
      - name: Build extensions
        run: gradle make makePluginsJson
      
      - name: Push builds
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -B builds
          git add **/build/*.cs3 build/plugins.json
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push -f origin builds          Whvx_API=your_api_key
          CatflixAPI=your_api_key
          ConsumetAPI=your_api_key
          FlixHQAPI=your_api_key
          WhvxAPI=your_api_key
          WhvxT=your_token
          SharmaflixApikey=your_api_key
          SharmaflixApi=your_api_key
          Theyallsayflix=your_api_key
          GojoAPI=your_api_key
          HianimeAPI=your_api_key
          Vidsrccc=your_api_key
          WASMAPI=your_api_key
          KissKh=your_api_key
          KisskhSub=your_api_key
          SUPERSTREAM_THIRD_API=your_api_key
          SUPERSTREAM_FOURTH_API=your_api_key
          SUPERSTREAM_FIRST_API=your_api_key
          StreamPlayAPI=your_api_key
          PROXYAPI=your_api_key
          KAISVA=your_api_key
          MOVIEBOX_SECRET_KEY_ALT=your_key
          MOVIEBOX_SECRET_KEY_DEFAULT=your_key
          KAIDEC=your_key
          EOF
      
      - name: Build extensions
        run: |
          chmod +x gradlew
          ./gradlew make makePluginsJson
      
      - name: Push builds
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -B builds
          git add **/build/*.cs3 build/plugins.json
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push -f origin builds          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -B builds
          git add *.cs3 plugins.json
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push -f origin builds
